# Generated by Django 4.2.25 on 2025-10-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_order_payment_screenshot_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='pic',
            field=models.CharField(max_length=200),
        ),
    ]
