# Generated by Django 4.2.25 on 2025-10-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_alter_menu_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='pic',
            field=models.ImageField(upload_to='fimage'),
        ),
    ]
